### ISSUE TITLE
Remove slopes along the edges of the waterfall

### ISSUE THREAD

**Issue by TarLink48** [sannysanoff/SDRPlusPlus#5]
Если возможно , убрать или сделать опциональным включение/отключение покатов по краям водопада , в частности на SDR Airspy H+ Discovery
![Снимок](https://user-images.githubusercontent.com/99340373/154845681-0353cc3e-0d0a-40bc-8bbb-4e648b4cbafe.PNG)
![Снимок2](https://user-images.githubusercontent.com/99340373/154845687-7a3fc60e-6905-4aee-ac71-60c77311ae25.PNG)

**Comment by sannysanoff** [comment]
done
